- name: Refresh all repos
  zypper_repository:
    repo: '*'
    runrefresh: yes
    auto_import_keys: true
  become: yes
- name: Update all packages
  zypper:
    name: '*'
    state: latest
  become: yes
- name: Install packages
  zypper:
    name: ['code',
          'MozillaThunderbird',
          'git',
          'gcc',
          'zsh',
          'make',
          'npm',
          'chromium',
          'fcitx-mozc',
    ]
    state: present
