- name: Refresh all repos
  zypper_repository:
    repo: '*'
    runrefresh: yes
    auto_import_keys: true
  become: yes
- name: Update all packages
  zypper:
    name: '*'
    state: latest
  become: yes
- name: Add vscode repo
  become: yes
  zypper_repository:
    name: Visual Studio Code
    repo: https://packages.microsoft.com/yumrepos/vscode
    auto_import_keys: yes
    disable_gpg_check: no
    state: present
- name: Install packages
  become: yes
  zypper:
    name: ['code',
          'MozillaThunderbird',
          'git',
          'gcc',
          'zsh',
          'make',
          'npm',
          'chromium',
          'fcitx-mozc',
          'bat',
          'vlc',
          'calibre',
          'gnome-tweaks',
          'the_silver_searcher',
          'nextcloud-client',
          'sqlite3',
          'gcc-c++',
          'autoconf',
    ]
    state: present
