- name: Refresh all repos
  zypper_repository:
    repo: '*'
    runrefresh: yes
    auto_import_keys: true
  become: yes
- name: Update all packages
  zypper:
    name: '*'
    state: latest
  become: yes
- name: Add vscode repo
  become: yes
  zypper_repository:
    name: Visual Studio Code
    repo: https://packages.microsoft.com/yumrepos/vscode
    auto_import_keys: yes
    disable_gpg_check: no
    state: present
- name: Install packages
  become: yes
  zypper:
    name: ['code',
          'MozillaThunderbird',
          'git',
          'gcc',
          'zsh',
          'make',
          'npm',
          'chromium',
          'fcitx-mozc',
          'bat',
          'vlc',
          'calibre',
          'gnome-tweaks',
          'the_silver_searcher',
          'nextcloud-client',
          'sqlite3',
          'gcc-c++',
          'steam',
          #'http://mirrors.ctan.org/support/texlive/texlive-dummy/openSUSE/texlive-dummy-2019.9999-1.noarch.rpm',
          'autoconf',
          'automake',
          'libtool',
          'jq',
          'go',
          'whois',
    ]
    state: present
- name: Get texlive from the official site
  get_url: url=http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz dest=/tmp/install-tl-unx.tar.gz

- name: Extract texlive installer
  unarchive: src=/tmp/install-tl-unx.tar.gz dest=/tmp

# See https://texwiki.texjp.org/?Linux#texliveinstall
# - name: Install texlive
#   become: yes
#   shell: ./install-tl -no-gui -repository http://mirror.ctan.org/systems/texlive/tlnet/ chdir=/tmp/install-tl-*
